import fs from 'fs';

const students = JSON.parse(fs.readFileSync('scripts/students.json', 'utf8'));

const initialDataTs = `import { Student, AttendanceRecord, DisciplineRecord, SpreadsheetConfig, TeacherUser } from '../types';

export const INITIAL_TEACHER: TeacherUser = {
  nip: '197410101998022001',
  name: 'Ulfatul Husna, S.Ag.,M.Pd.',
  subject: 'Pendidikan Agama Islam dan Budi Pekerti',
  school: 'SMA Negeri 1 Krembung',
  schoolYear: '2026-2027',
};

// 282 Siswa Resmi SMAN 1 Krembung (X-1 s/d X-4 dan XII-9 s/d XII-12)
export const INITIAL_STUDENTS: Student[] = ${JSON.stringify(students, null, 2)};

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    studentId: 'std-1',
    studentNisn: '3104161443',
    studentName: 'ABIMANA HIDAYA JATI',
    className: 'X-1',
    activity: 'Sholat Dhuha',
    date: '2026-10-02',
    time: '06:45:12',
    status: 'Hadir',
    method: 'QR_SCAN',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
  {
    id: 'att-2',
    studentId: 'std-2',
    studentNisn: '3106614120',
    studentName: 'AHMAD AZAM MUSYAFFA',
    className: 'X-1',
    activity: 'Sholat Dhuha',
    date: '2026-10-02',
    time: '06:46:05',
    status: 'Hadir',
    method: 'QR_SCAN',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
  {
    id: 'att-3',
    studentId: 'std-36',
    studentNisn: '0102705982',
    studentName: 'ACHMAD ABIMANYU',
    className: 'X-2',
    activity: 'Pembelajaran',
    date: '2026-10-02',
    time: '07:30:00',
    status: 'Hadir',
    notes: 'Materi: Bab Berpikir Kritis & Cinta Iptek (QS Ali Imran 190-191)',
    method: 'MANUAL',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
  {
    id: 'att-4',
    studentId: 'std-140',
    studentNisn: '11765',
    studentName: 'ADINDA BILQIS ANNAZWA',
    className: 'XII-9',
    activity: 'Sholat Dzuhur Berjama’ah',
    date: '2026-10-02',
    time: '12:05:40',
    status: 'Hadir',
    method: 'QR_SCAN',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
  {
    id: 'att-5',
    studentId: 'std-176',
    studentNisn: '11656',
    studentName: 'AKBAR FIRLY ERLANGGA',
    className: 'XII-10',
    activity: 'Istighotsah',
    date: '2026-10-02',
    time: '06:30:22',
    status: 'Hadir',
    method: 'QR_SCAN',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
  {
    id: 'att-6',
    studentId: 'std-211',
    studentNisn: '11841',
    studentName: 'AKIFA NAJWA AZ ZAHRA',
    className: 'XII-11',
    activity: 'Khotmil Qur’an',
    date: '2026-10-01',
    time: '06:40:15',
    status: 'Hadir',
    notes: 'Tadarus Juz 15 tartil dan fasih',
    method: 'QR_SCAN',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
  {
    id: 'att-7',
    studentId: 'std-247',
    studentNisn: '11987',
    studentName: 'ALIF FATUR ROHMAN',
    className: 'XII-12',
    activity: 'Sholat Ashar Berjama’ah',
    date: '2026-10-02',
    time: '15:15:00',
    status: 'Hadir',
    method: 'QR_SCAN',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    syncedToSpreadsheet: true,
  },
];

export const INITIAL_DISCIPLINE: DisciplineRecord[] = [
  {
    id: 'disc-1',
    studentId: 'std-1',
    studentNisn: '3104161443',
    studentName: 'ABIMANA HIDAYA JATI',
    className: 'X-1',
    category: 'Ringan',
    points: 5,
    violation: 'Lupa membawa perlengkapan sholat (sarung) pada Sholat Dzuhur Berjama\'ah',
    date: '2026-09-28',
    time: '12:10:00',
    followUp: 'Peringatan lisan & peminjaman sarung inventaris musholla, diingatkan pentingnya kesiapan ibadah.',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    status: 'Terbina / Selesai',
    syncedToSpreadsheet: true,
  },
  {
    id: 'disc-2',
    studentId: 'std-141',
    studentNisn: '11695',
    studentName: 'AHMAD GATHFAN TAZAKKA EFENDI',
    className: 'XII-9',
    category: 'Sedang',
    points: 15,
    violation: 'Tidak hadir dalam Sholat Dzuhur Berjama\'ah tanpa uzur syar\'i yang sah',
    date: '2026-09-30',
    time: '12:20:00',
    followUp: 'Bimbingan konseling PAI (Deep Learning - Mindful Ibadah) dan penugasan rangkuman adab sholat berjamaah.',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    status: 'Dalam Pembinaan',
    syncedToSpreadsheet: true,
  },
  {
    id: 'disc-3',
    studentId: 'std-53',
    studentNisn: '0113490214',
    studentName: 'FACHRI AHMAD MAULANA YUSUF',
    className: 'X-2',
    category: 'Ringan',
    points: 5,
    violation: 'Terlambat mengikuti Istighotsah Jumat pagi 15 menit',
    date: '2026-10-02',
    time: '06:45:00',
    followUp: 'Diberikan motivasi kedisiplinan waktu pagi dan dzikir mandiri setelah acara selesai.',
    teacher: 'Ulfatul Husna, S.Ag.,M.Pd.',
    status: 'Terbina / Selesai',
    syncedToSpreadsheet: true,
  },
];

export const INITIAL_SPREADSHEET_CONFIG: SpreadsheetConfig = {
  webhookUrl: 'https://script.google.com/macros/s/AKfycbx_SMANIKRE_SIAP_PAI_PROXY/exec',
  spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
  sheetNamePresensi: 'Data_Presensi_PAI',
  sheetNameDisiplin: 'Catatan_Kedisiplinan',
  autoSync: true,
  lastSyncTime: '2026-10-02 14:30 WIB',
  totalSyncedRows: 10,
};
`;

fs.writeFileSync('src/data/initialData.ts', initialDataTs);
console.log('src/data/initialData.ts updated with', students.length, 'students');
